##################################################################################
#####################STAGING_ENVIRONMENT_DEPLOYMENT#######################
###################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
  labels:
    app: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
      - name: selenium
        image: selenium/:4.0
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /wd/status
            port: 4404
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5